name: thermo-ml
channels: [conda-forge, pytorch]
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - matplotlib
  - seaborn
  - pymatgen
  - mp-api
  - pip
  - pip:
      - matminer
      - torch
      - nbstripout
